fix(webhook-slash): remove comment about root path
twilight-rs/examples pull request #3
Opened 2021-09-19 18:19 UTC by aetheryx

Discord has added support for non-root paths

2021-09-19 18:20 UTC, Erk- approved these changes

2021-09-19 18:23 UTC, vilgotf commented
Shouldn't this check be removed all together?

2021-09-19 18:24 UTC, Erk- commented
Not nessesarily, this is just an example so it in my opinion also shows that you could filter by other subdomains if you want to

2021-09-30 15:33 UTC, 7596ff commented
> you could filter by other subdomains if you want to

Can we add a note about this as well?

2021-10-03 15:38 UTC, 7596ff requested changes

2021-10-03 15:38 UTC, 7596ff commented on webhook-slash/src/main.rs
> +    // Check if the path the request is sent to is the root of the domain.
```suggestion
    // Check if the path the request is sent to is the root of the domain.
    //
    // This filter is for the purposes of this example. The user may filter by
    // any subdomain they choose.
```

2021-10-03 15:45 UTC, Erk- approved these changes

2021-10-03 15:47 UTC, 7596ff approved these changes

2021-10-03 15:47 UTC, merged